---
version: "2"

services:
  app:
    build: .
    environment:
      - MONGO_USER=root
      - MONGO_PASS=gfhjkm
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    volumes:
      - .:/code
      - ./icons:/icons
    ports:
      - "8080:8080"

  parser:
    build: ./parser
    environment:
      - MONGO_USER=root
      - MONGO_PASS=gfhjkm
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REPARSE_EVERY_DAYS=5
      - DB_READ_DELAY=5
      - DB_READ_COUNT=100
    volumes:
      - ./parser:/code
      - ./icons:/icons

  mongo:
    image: mongo
    command: --smallfiles
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: gfhjkm

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: gfhjkm
